INSERT INTO USER (BIO, EMAIL, IMAGE, PASSWORD, USERNAME) 
	VALUES ('bio', 'robinly@tw.ibm.com', null, null, 'robinly');

INSERT INTO USER (BIO, EMAIL, IMAGE, PASSWORD, USERNAME) 
	VALUES ('bio', 'yap@tw.ibm.com', null, null, 'yap');

INSERT INTO FOLLOW_REF (FOLLOW, USER) VALUES (2,1);

INSERT INTO ARTICLE (BODY, CREATED_AT, DESCRIPTION, SLUG, TITLE, UPDATED_AT, USER_ID) 
	VALUES ('tunisia is nice', CURRENT_TIMESTAMP, 'biz trip', 'tunisia-is-nice', 'title', CURRENT_TIMESTAMP, 1);
	
INSERT INTO COMMENT (BODY, ARTICLE_ID, USER_ID, CREATED_AT, UPDATED_AT)
	VALUES ('comment1', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO COMMENT (BODY, ARTICLE_ID, USER_ID, CREATED_AT, UPDATED_AT)
	VALUES ('comment2', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO tag (name) VALUES ('spring');

INSERT INTO tag (name) VALUES ('boot');

INSERT INTO article_tag VALUES (1,1,1);
INSERT INTO article_tag VALUES (1,2,2);

INSERT INTO article_favorite VALUES (1,2);